name: Build Pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Update Pip
      run: python -m pip install --upgrade pip
    - name: Install Python Dependencies
      run: python -m pip install -r ./python/requirements.txt
    - name: Install Javascript Dependencies
      run: npm install --package-lock
    - name: Convert Notebook to Script
      run: jupyter nbconvert --to script ./python/notebook.ipynb
    - name: Run Python Script
      run: python ./python/notebook.py
    - name: Run Build Pages Script
      run: sh build-pages.sh
    - name: Publish to Github Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './public/'
